export const WECHART = 'WECHART'
export const Change_Title = 'Change_Title'
export const Change_Content = 'Change_Content'
export const Change_Url = 'Change_Url'
export const Change_Logo = 'Change_Logo'
export const Change_Pic = 'Change_Pic'
export const Change_Txt = 'Change_Txt'
export const Add_Pic = 'Add_Pic'
export const Add_Short = 'Add_Short'

