export const UPDATE_SEARCH_MENU_LIST = "UPDATE_SEARCH_MENU_LIST"
export const CHANGE_FILTER_MENU_LIST = "CHANGE_FILTER_MENU_LIST"
export const HIDE_FILTER_MENU_LIST = "HIDE_FILTER_MENU_LIST"
export const CHANGE_SHOW_MENU_LIST = "CHANGE_SHOW_MENU_LIST"